#MobsToSpawn
MobsSpawnWtf:
  0: "ZOMBIE"
  1: "BLAZE"
  2: "SLIME"
  3: "ENDERMITE"
  4: "MAGMA_CUBE"
  5: "ZOMBIE_PIGMAN"
  6: "CAVE_SPIDER"
  7: "CREEPER"
  8: "ENDERMAN"
  9: "EVOCATION_ILLAGER"
  10: "GHAST"
  11: "GIANT"
  12: "GUARDIAN"
  13: "HUSK"
  14: "SHULKER"
  15: "SILVERFISH"
  16: "SPIDER"
  17: "STRAY"
  18: "VEX"
  19: "VINDICATION_ILLAGER"
  20: "WITCH"
  21: "WITHER_SKELETON"
  22: "ZOMBIE_VILLAGER"
  23: "ILLUSION_ILLAGER"

Lifes: 2